### PR TITLE
A few h2spec fixes

### PR DESCRIPTION
**Pull request by jeromegn**
Hey there,

I thought I'd work on this project a little bit. I ran the h2spec and found 13 failing tests.

I fixed 5 of those. Most of them were easy picking:
- `generic/2/2` - Sends a WINDOW_UPDATE frame on half-closed (remote) stream
- `generic/2/3` - Sends a PRIORITY frame on half-closed (remote) stream
- `generic/3.9/1` - Sends a WINDOW_UPDATE frame with stream ID 0
- `generic/3.9/2` - Sends a WINDOW_UPDATE frame with stream ID 1
- `http2/8.1.2.3/1` - Sends a HEADERS frame with empty ":path" pseudo-header field

There are still 8 broken tests!

There's one with setting the initial window size. I think you're doing that right, but the test fails because it's getting an old stream instead of a new one (I think.)

A lot of http2 is way over my head, but it seems far more doable when using `h2spec`.

There are some hpack issues, they don't seem too hard to fix.

### CODE REVIEW

**Comment by ysbaddaden** [comment]
I specifically didn't run crystal format because of the removed line between large case blocks, which makes things harder to read. Can you revert that?

**Comment by ysbaddaden** [comment]
And thank you for trying to jump into HTTP/2. It's far above my own head, too :/

**Comment by jeromegn** [comment]
@ysbaddaden just reverted the crystal formatting. My editor runs that by default on save.

Technically, does passing h2spec means it's complete? 8 failures seems very low. I only spent an hour or so on this to fix those 5, albeit easy, ones.

**Comment by ysbaddaden** [comment]
I commited the empty `:path` header as c8cc094ba6d7cc24a53fdf01e78f268462690809 but I can't find the fixes for the other cases?

**Comment by jeromegn** [comment]
I can't remember, it's been a bit too long :)

I think most of them were a simple fix. If these exact changes in this PR don't make those h2spec pass, then it's probably best not to merge and close this.

Are you picking this back up? I think it'd do wonders for Crystal's popularity if it had http2 support out of the box.

**Comment by ysbaddaden** [comment]
It broke with recent Crystal versions, and fixed it. 

I fixed some failures that a new version of h2spec catched: empty `:path` header, PRIORITY frames for future streams, invalid Huffman string padding.

I must still fix the "must respect window update" for sending data... The IO::CircularBuffer is ready, but I feel lazy to out this is place.

**Comment by ysbaddaden** [comment]
Oh, I did respect the "window size" and window update increments, but it was always failing. The fix was easy: aa7d4bdfad7ca38bcd212c1cd9d1492373318bd7

**Pull request closed without merging**
